# Generated by Django 4.2.3 on 2023-07-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintodoapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
